version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-gerion"
resolve_s3 = true
s3_prefix = "sam-app-gerion"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
