version = 0.1
[default.deploy.parameters]
stack_name = "apigateway-lambda-sample"
resolve_s3 = true
s3_prefix = "apigateway-lambda-sample"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
