AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

#テンプレートの説明
Description: apigateway-lambda-sample

#共通パラメータ
Globals:
  Function:
    Tracing: Active
    MemorySize: 512
    Timeout: 30
  Api:
    TracingEnabled: true
    
Resources:

  #api gatewayの定義
  ApiDynamoTest:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods

  #lambdaの定義 
  LambdaFuntionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: hello.lambda_handler
      Runtime: python3.9

      Events:
        InputFunctionEvent:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: !Ref ApiDynamoTest

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Enabled: true
      Name: !Sub 'api-key'
      StageKeys: 
        - RestApiId: !Ref ApiDynamoTest
          StageName: Prod

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiKey
    Properties:
      ApiStages:
          - ApiId: !Ref ApiDynamoTest
            Stage: Prod
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      UsagePlanName: !Sub 'api-plan'

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - ApiUsagePlan
      - LambdaFuntionGet
    Properties : 
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan


Outputs:
  GetApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !Sub "https://${ApiDynamoTest}.execute-api.${AWS::Region}.amazonaws.com/Prod/get"

  MyApiKeyOutput:
    Description: API Key information
    Value: !Ref ApiKey
    Export:
      Name: ApiKey