AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

#テンプレートの説明
Description: apigateway-lambda-sample

#共通パラメータ
Globals:
  Function:
    Tracing: Active
    MemorySize: 512
    Timeout: 30
  Api:
    TracingEnabled: true
    
Resources:

  #api gatewayの定義
  ApiDynamoTest:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: MyUsagePlan
          Quota:
            Limit: 10000
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 100

  #lambdaの定義 
  LambdaFuntionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: hello.lambda_handler
      Runtime: python3.9

      Events:
        InputFunctionEvent:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: !Ref ApiDynamoTest

Outputs:
  GetApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !Sub "https://${ApiDynamoTest}.execute-api.${AWS::Region}.amazonaws.com/Prod/get"