AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  apigateway-lambda-sample
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true
    
Resources:

  #api gatewayの定義
  InputApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL

  #lambdaの定義 
  InputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: input-test.lambda_handler
      Runtime: python3.9
      
      MemorySize: 512
      Timeout: 300

      Events:
        InputFunctionEvent:
          Type: Api
          Properties:
            Path: /input
            Method: GET
            RestApiId: !Ref InputApi

      #IP制限
      Environment:
        Variables:
          ALLOWED_IPS: "192.168.1.1,xxx.xxx.xxx.xxx"

Outputs:
  InputApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !Sub "https://${InputApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/input"
